### ISSUE TITLE
Route plan reversing/duplicating fixes

### ISSUE THREAD

**Issue by kellpossible** [thlytras/rfgfs#1]
Hi, just checking out this fantastic code you've written. Had an issue generating a plan where it would put waypoints going backwards along a route:

`plan <- planRoute("YMHB", "NZQN", fixes=c("PECOB", "FONLO", "BUGBA"))`

`fix    fixLat   fixLon           fullName  freq range elevation dev
1   YMHB -42.83617 147.5118             Hobart    NA    NA        12  NA
2     HB -42.84712 147.5267     HOBART VOR-DME 11270   130        48  14
3  PECOB -43.16194 150.9369               <NA>    NA    NA        NA  NA
4  FONLO -43.48111 157.7744               <NA>    NA    NA        NA  NA
5  ELGUN -43.44856 163.0000               <NA>    NA    NA        NA  NA
6  KABIN -43.15103 168.5522               <NA>    NA    NA        NA  NA
7  SUPRA -42.91822 166.5489               <NA>    NA    NA        NA  NA
8  OMKIN -42.41439 163.0000               <NA>    NA    NA        NA  NA
9  ADKOS -44.61711 166.8804               <NA>    NA    NA        NA  NA
10 BUGBA -43.81561 163.0000               <NA>    NA    NA        NA  NA
11 ADKOS -44.61711 166.8804               <NA>    NA    NA        NA  NA
12    SH -44.98411 168.7826 SLOPE HILL VOR-DME 11360    50      1394  24
13  NZQN -45.02055 168.7454         Queenstown    NA    NA      1171  NA
    magdecl       dist    course magcourse  awy baseFL topFL altawy
1  15.04356   1.719517 135.14931 120.10575  SID     NA    NA     NA
2  14.97280 280.223330  98.35569  83.38289 M643    180   600     NA
3  16.82900 555.592859  96.01389  79.18490 M643    245   600     NA
4  19.93623 422.816389  91.30656  71.37033 M643    245   600     NA
5  21.62235 451.652299  87.69684  66.07449 M643    245   600     NA
6  22.75610 165.292057 278.34895 255.59285 L508    245   600     NA
7  22.14670 296.241273 279.72156 257.57486 L508    245   600     NA
8  20.87837 397.701406 129.37659 108.49821 P766    245   600     NA
9  23.53264 322.579191 284.71711 261.18446 P753    245   600     NA
10 21.89700 322.579191 107.42381  85.52681 P753    245   600     NA
11 23.58282 155.916599 105.88027  82.29745 P753    160   600     NA
12 24.39322   4.998831 215.84838 191.45516 STAR     NA    NA     NA
13 24.41599         NA        NA        NA <NA>     NA    NA     NA
`

ADKOS is listed twice (going backwards and forwards)

**Comment by kellpossible** [comment]
mind you this is on a route where the airways don't intersect, so perhaps this is to be expected!

**Comment by thlytras** [comment]
Hi there! You figured it out correctly. The function tries to find the shortest route from FONLO to BUGBA (and then towards NZQN) **along ICAO runways**. Thus it flies FONLO -> ELGUN -> KABIN -> SUPRA -> OMKIN -> ADKOS -> BUGBA, and then BUGBA -> ADKOS -> SH -> NZQN.

However, you can insert a NA in your `fixes` argument between those fixes that are not joined by an ICAO runway, i.e.:
`plan <- planRoute("YMHB", "NZQN", fixes=c("PECOB", "FONLO", NA, "BUGBA"))`
This should give you your intended flight plan!

**Comment by kellpossible** [comment]
thanks, I will try this tip next time!
